accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    path('login/', auth_views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
]

autre/urls.py
from django.urls import path
from . import views

app_name = 'autre'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('ajouter_article', views.ajouter_article, name='ajouter_article'),
]

horaires/urls.py
from django.urls import path
from . import views

app_name = 'horaires'
urlpatterns = [
    path('', views.index, name='index'),
]

projetun/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
import django
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('choses/', include('choses.urls')),
    path('accounts/', include('accounts.urls')),
    path('autre/', include('autre.urls')),
    path('horaires/', include('horaires.urls')),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

accounts/models.py
from django.db import models

# Create your models here.

autre/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import User
m = User.objects.filter(username='marcel')[0]


class Article(models.Model):
    titre = models.CharField(max_length=200)
    contenu = models.TextField()
    auteur = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    photo = models.ImageField(upload_to='testons', default='a.jpg')

    def __str__(self):
        return self.titre

    def __unicode__(self):
        return self.titre

horaires/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', max_length=100)

autre/forms.py
from django import forms


class ArticleForm(forms.Form):
    titre = forms.CharField(label='titre', max_length=100)
    contenu = forms.CharField(label='contenu', max_length=200, widget=forms.Textarea)
    photo = forms.FileField()

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
'''
from .forms import LoginForm
# Create your views here.
def login_view(request):
    if request.method =='POST':
        form = LoginForm(request.POST)
        rz
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                next_url = request.GET.get('next')
                if next_url:
                    return HttpResponseRedirect(next_url)
                return(HttpResponse('youpi'))
    else:
        form = LoginForm()

    return render(request, 'accounts/name.html', {'form': form})
'''

def logout_view(request):
    logout(request)
    return(HttpResponseRedirect(reverse('autre:index')))

@login_required
def profile(request):
    return render(request, 'accounts/profile.html', {'user': request.user})
        

autre/views.py
from django.shortcuts import render
from django.views import generic
from .models import Article
from . import monkey_patching
from .forms import ArticleForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.



class IndexView(generic.ListView):
    template_name = 'autre/index1.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.all()


class DetailView(generic.DetailView):
    template_name = 'autre/detail1.html'
    model = Article


class AjouterArticleView(generic.FormView):
    form_class = ArticleForm
    success_url = '.'
    template_name = 'autre/ajouter_article1.html'
    
    def form_valid(self, form):
        titre = self.request.POST['titre']
        contenu = self.request.POST['contenu']
        photo = self.request.FILES['photo']
        nouvel_article = Article(photo=photo, titre=titre,
        contenu=contenu, auteur=self.request.user)
        nouvel_article.save()
        return super().form_valid(form)


ajouter_article = login_required(AjouterArticleView.as_view())

horaires/views.py
from django.shortcuts import render
from .main import Allosession
# Create your views here.
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    a = Allosession()
    return render(request, 'horaires/index.html', {'dico':a.dico})

accounts/templates/accounts/name.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

<form action="." method="post">
{% csrf_token %}
{{form}}
<input type="submit" value="Submit" />
</form>

</body>
</html>

accounts/templates/accounts/profile.html
{% extends "autre/base_autre1.html" %}

{% block contenu %}
<h1> {{user.username}} </h1>
<h3> {{ user.get_number_articles }} </h3>
{% endblock %}

autre/templates/autre/ajouter_article.html
{% extends 'base.html' %}

{% block contenu %}
<form  method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Submit" />
</form>

{% endblock %}

autre/templates/autre/ajouter_article1.html
{% extends 'autre/base_autre1.html' %}

{% block contenu %}
<form  method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Submit" />
</form>

{% endblock %}

autre/templates/autre/base_autre1.html
{% extends "base1.html" %}

{% block menu_av_ut %}
{% if user.is_authenticated %}
<span> <a href="{% url 'autre:ajouter_article' %}"> Ecrire </a> </span>
<p> <a href="{% url 'horaires:index' %}"> Horaires de cinémas </p>
{% endif %}
{% endblock %}

autre/templates/autre/detail.html
{% extends "base.html" %}

{% block contenu %}

<h1> {{article.titre}} </h1>

<p> {{article.contenu}} </p>

<img src= {{article.photo.url}} height="200" width="200" />
<br />
<a href={% url 'autre:index' %}> Retour </a>
{% endblock %}

<p> zerfzef </p>

autre/templates/autre/detail1.html
{% extends "autre/base_autre1.html" %}
{% load static %}




{% block contenu %}

<div class="container">
                	<div class="wrapper-inner">
                    	<!-- details-image -->
                    	<h1> {{article.titre}} </h1>
                    	<figure class="details-image">
                        	<img src= {{article.photo.url}} alt="" class="img-responsive"/>
                        </figure>
                        <!-- details-image -->
                        <!-- content -->
                        <div class="details-content">
                        	<!-- left -->
                        	<section class="inner-left">
                            	<header>
                                	
                                    <h4>{{article.titre}}</h4>
                                    <h5>{{article.auteur}}</h5>
                                </header>
                            </section>
                            <!-- left -->
                            <!-- right -->
                            <section class="inner-right">
                            	{{article.contenu}}
                               <!-- <header>
                                    <h2>Camera Used</h2>
                                    <h3>Nikon F56DSLR</h3>
                                </header> -->
                            </section>
                            <!-- right -->
                        </div>
                        <!-- content -->
                        <!-- details-image -->
                        <figure class="details-image">
                        	<img src="images/details-image-2.jpg" alt="" class="img-responsive"/>
                        </figure>
                        <!-- details-image -->
                        <!-- details-image -->
                        <figure class="details-image">
                        	<img src="images/details-image-3.jpg" alt="" class="img-responsive"/>
                        </figure>
                        <!-- details-image -->
                    </div>
                </div>



{% endblock %}

autre/templates/autre/index.html
{% extends "base.html" %}
{% load static %}



{% block contenu %}
<div class="w3-row-padding w3-padding-16 w3-center" id="food">

{% for article in articles %}
    <div class="w3-quarter">
      
      <h3> <a href={% url 'autre:detail' article.id %} > {{ article.titre }} </a> </h3>
      <p> by {{article.auteur}} <p>
      <p> {{ article.contenu }} </p>
      
    </div>
{% endfor %}
</div>
  
{% endblock %}



{% block about %}

<a href='ajouter_article'> + </a>

{% endblock %}

{% block footer %}
Hello
{% endblock %}

autre/templates/autre/index1.html
{% extends 'autre/base_autre1.html' %}

{% block contenu %}

{% for article in articles %}
<li class="masonry-item grid">
          <figure class="effect-sarah"> <img src={{article.photo.url}} alt="" />
            <figcaption>
              <h2> {{article.titre}} </span></h2>
              <p>par {{article.auteur}}</p>
              <a href="{% url 'autre:detail' article.id %}">View more</a> 
             </figcaption>
          </figure>
</li>
{% endfor %}

{% endblock %}

horaires/templates/horaires/index.html
{% extends 'autre/base_autre1.html' %}


{% block contenu %}
<h1> Horaires des cinémas : </h1>
{% for nom_cinema,cinema in dico.items %}

    <h2>{{nom_cinema}}</h2>
    {% for film in cinema %}
        <p>{{film.titre}} ({{film.directors}})  {{film.join_horaires}}</p>
    {% endfor %}
    <br />

{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>

<html>
<title> Moutarde et Cinéma</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Sidebar (hidden by default) 
<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()"
  class="w3-bar-item w3-button">Close Menu</a>
  <a href="#food" onclick="w3_close()" class="w3-bar-item w3-button">Food</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">About</a>
</nav>
-->
<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <!--
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
    -->
    <div class="w3-right w3-padding-16">
    
    {% block utilisateur %}
    {% if user.is_authenticated %}
    <a href={% url 'accounts:profile' %} >{{user.username}}</a> <a href={% url 'accounts:logout' %} > logout </a>
    {% else %}
    <a href={% url 'accounts:login' %}> login </a>
    {% endif %}
    {% endblock %}
    </div>
    <div class="w3-center w3-padding-16"> <a href={% url 'autre:index' %}> Moutarde et Cinéma </a> </div>
  </div>
</div>
  
<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

    {% block contenu %}

    {% endblock %}

  <!-- Pagination -->
  
  <!--
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>
  //-->
  <hr id="about">

  <!-- About Section -->
  
  <div class="w3-container w3-padding-32 w3-center">  
  {% block about %}
   
    {% endblock %}
    </div>
  </div>
  <hr>
  
  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
  {% block footer %}
  <!-- 
    <div class="w3-third">
      <h3>FOOTER</h3>
      <p>Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>
  
    <div class="w3-third">
      <h3>BLOG POSTS</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Lorem</span><br>
          <span>Sed mattis nunc</span>
        </li>
        <li class="w3-padding-16">
          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Ipsum</span><br>
          <span>Praes tinci sed</span>
        </li> 
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR TAGS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dinner</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">France</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Drinks</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Flavors</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Cuisine</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Chicken</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dressing</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fried</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Duck</span>
      </p>
    </div>
    //-->
    {% endblock %}
  </footer>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
}
 
function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>

<html class="no-js"  lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<title> Moutarde et Cinéma </title>

<!-- Normalize -->

<link rel="stylesheet" href="{% static 'css/assets/normalize.css'%}" type="text/css">

<!-- Bootstrap -->

<link href="{% static 'css/assets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

<!-- Font-awesome.min -->

<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

<!-- Effet -->

<link rel="stylesheet" href="{% static 'css/gallery/foundation.min.css' %}"  type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'css/gallery/set1.css' %}" />

<!-- Main Style -->

<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

<!-- Responsive Style -->

<link href= "{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->

<!--[if lt IE 9]>

      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

<script src="js/assets/modernizr-2.8.3.min.js" type="text/javascript"></script>
</head>

<body>

<!-- header -->

<header id="header" class="header">
  <div class="container-fluid">
    <hgroup> 
      
      <!-- logo -->
      
      <h1> <a href="{% url 'autre:index' %}" title="Moutarde"><img src="{% static 'images/logo.png' %}" alt="M&C" title="Picxa"/></a> </h1>
      
      <!-- logo --> 
      
      {% block menu_av_ut %}
            {% endblock %}
            
            {% block utilisateur %}
            {% if user.is_authenticated %}
            <span> <a href={% url 'accounts:profile' %} >{{user.username}}</a> <a href={% url 'accounts:logout' %} > (✘) </a> </span>
            {% else %}
            <a href={% url 'accounts:login' %}> login </a>
            {% endif %}
            {% endblock %}
      
      <!-- nav -->
      
      <nav>
        <div class="menu-expanded">
          <div class="nav-icon">
            <div id="menu" class="menu"></div>
            
            
            <span> menu </span>
          </div>
          
          <div class="main-menu">
            <ul>
              <li class="active"><a href="index.html">Home</a></li>
              <li><a href="about.html">About</a></li>
              <li><a href="blog.html">blog</a></li>
              <li><a href="contact.html">contact</a></li>
            </ul>
          </div>
        </div>
      </nav>
      
      <!-- nav --> 
      
    </hgroup>
  </div>
</header>

<!-- header -->

<main class="main-wrapper" id="container"> 
  
  <!-- image Gallery -->
  
  <div class="wrapper">
    <div class="">
      <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-3 masonry">
       
       {% block contenu %}
       {% endblock %}
      </ul>
    </div>
  </div>
</main>

<!-- Image Gallery --> 

<!-- footer -->

<footer class="footer">
  
</footer>

<!-- footer --> 

<!-- jQuery --> 

</body>
</html>